apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: project-trigger-template
spec:
  params:
    - name: git-repo-url
      description: URL to the git repo to be cloned
    - name: path-to-context
      description: The path to the build context, used by Kaniko
      default: .
    - name: path-to-manifest-file
      description: The path to the yaml file describe how to deploy the application.
      default: manifest.yaml
    - name: api-url
      description: The api url for interacting with ibm cloud
      default: cloud.ibm.com
    - name: ibm-cloud-region
      description: The region where the cluster resides
      default: us-south
    - name: cf-target-url
    - name: cf-org
    - name: cf-space
    - name: cf-app
    - name: ibmcloud-api
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-t
      spec:
        serviceAccountName: service-account
        pipelineRef:
          name: project-pipeline
        params:
          - name: path-to-context
            value: $(params.path-to-context)
          - name: path-to-manifest-file
            value: $(params.path-to-manifest-file)
          - name: api-url
            value: $(params.api-url)
          - name: ibm-cloud-region
            value: $(params.ibm-cloud-region)
          - name: git-repo-url
            value: $(params.git-repo-url)
          - name: cf-target-url
            value: $(params.cf-target-url)
          - name: cf-org
            value: $(params.cf-org)
          - name: cf-space
            value: $(params.cf-space)
          - name: cf-app
            value: $(params.cf-app)
          - name: cf-target-url
            value: $(params.cf-target-url)
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
        workspaces:
          - name: git-repo
            persistentVolumeClaim:
              claimName: $(uid)-pvc
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: $(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: project-pipeline
spec:
  params:
    - name: api-url
    - name: git-repo-url
    - name: path-to-context
    - name: path-to-manifest-file
    - name: ibm-cloud-region
    - name: cf-org
    - name: cf-space
    - name: cf-app
    - name: cf-target-url
    - name: ibmcloud-api
  workspaces:
    - name: git-repo
      description: Workspace for holding the cloned source code from the git-repo
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone-repo
      params:
        - name: git-access-token
          value: public
        - name: branch
          value: main
        - name: repository
          value: $(params.git-repo-url)
      workspaces:
        - name: output
          workspace: git-repo
    - name: build-artifact-from-source
      taskRef:
        name: gradle-build-java-artifact-from-source
      runAfter:
        - git-clone
      params:
        - name: path-to-context
          value: $(params.path-to-context)
      workspaces:
        - name: source
          workspace: git-repo
    - name: deploy-artifact-to-ibm-cloud-foundry
      taskRef:
        name: cf-deploy-app
      runAfter:
        - build-artifact-from-source
      params:
        - name: cf-org
          value: $(params.cf-org)
        - name: cf-space
          value: $(params.cf-space)
        - name: cf-app
          value: $(params.cf-app)
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: cf-target-url
          value: $(params.cf-target-url)
      workspaces:
        - name: source
          workspace: git-repo
