apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cf-deploy-app
spec:
  params:
    - name: ibmcloud-api
      default: cloud.ibm.com
    - name: ibmcloud-region
    - name: ibmcloud-rg
    - name: cf-org
    - name: cf-space
    - name: cf-app
    - name: cf-target-url
  workspaces:
    - name: source
  steps:
    - name: deploy-app
      image: 'icr.io/continuous-delivery/pipeline/pipeline-base-image:2.6'
      env:
        - name: IBMCLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: secure-properties
              key: apikey
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          pwd;
          echo $(params.cf-target-url);
          echo $(params.cf-org);
          echo $(params.cf-space);
          echo $(params.ibmcloud-rg)

          ls -l $(workspaces.source.path);
          ibmcloud login -a $(params.ibmcloud-api) -r $(params.ibmcloud-region) -g $(params.ibmcloud-rg);
          ibmcloud target --cf-api $(params.cf-target-url) -o $(params.cf-org) -s $(params.cf-space);
          ibmcloud cf apps;
          ibmcloud cf push -f $(workspaces.source.path)/manifest.yaml $(params.cf-app);
